version: '3.8'
services:
  server:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    container_name: ds_download_server
    volumes:
      - ./server/:/srv/www/server/
    ports:
      - 8000:8000

  nginx:
    image: nginx
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/ssl/ds-download.test.crt:/etc/ssl/ds-download.test.crt
      - ./conf/ssl/ds-download.test.key:/etc/ssl/ds-download.test.key
      - ./conf/nginx/dhparam.pem:/etc/ssl/dhparam.pem
    ports:
      - 80:80
      - 443:443
    container_name: ds_download_nginx
    depends_on:
      - cms
      - django