version: '3.8'
services:
  server:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    container_name: ds_download_server
    volumes:
      - ./server/:/srv/www/server/
      - ~/corral-repl/tacc/NHERI:/corral-repl/tacc/NHERI
    ports:
      - 8000:8000

  nginx:
    image: nginx
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/ssl/ds-download.test.crt:/etc/ssl/api.crt
      - ./conf/ssl/ds-download.test.key:/etc/ssl/api.key
      - ./conf/nginx/dhparam.pem:/etc/ssl/dhparam.pem
    ports:
      - 80:80
      - 443:443
    container_name: ds_download_nginx

  redis:
    image: redis:6.2-alpine
    container_name: ds_download_redis
    hostname: ds_download_redis